# Generated by Django 4.2.5 on 2023-11-28 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Descripción', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Código', models.CharField(max_length=5)),
                ('Descripción', models.CharField(blank=True, max_length=1000)),
                ('Categoría Superior', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Disponibilidad', models.CharField(choices=[('E', 'Excelente'), ('C', 'Común'), ('P', 'Pobre'), ('R', 'Raro'), ('A', 'Fuerzas Armadas'), ('X', 'Experimental')], default='C', max_length=1)),
                ('Disimulo', models.CharField(choices=[('P', 'Bolsillo'), ('J', 'Chaqueta'), ('L', 'Chaqueta Larga'), ('N', 'No')], default='J', max_length=2)),
                ('Precisión', models.IntegerField()),
                ('Fiabilidad', models.CharField(choices=[('VR', 'Muy Fiable'), ('ST', 'Fiable'), ('UR', 'Poco Fiable')], default='ST', max_length=2)),
                ('Alcance', models.IntegerField(blank=True, null=True)),
                ('# Disparos', models.IntegerField(blank=True, null=True)),
                ('VD', models.IntegerField(blank=True, null=True)),
                ('Daño', models.CharField(max_length=20)),
                ('Peso', models.FloatField()),
                ('Precio', models.IntegerField()),
                ('Categoría', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category')),
                ('Marca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.brand')),
            ],
        ),
    ]
