# Generated by Django 4.2.5 on 2023-11-28 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Descripción',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='Nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Descripción',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Precio',
            new_name='accuracy',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Disponibilidad',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Categoría',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Disimulo',
            new_name='concealment',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Precisión',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Daño',
            new_name='damage',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='# Disparos',
            new_name='range',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Fiabilidad',
            new_name='reliability',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Alcance',
            new_name='rof',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='VD',
            new_name='shots',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='Peso',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Categoría Superior',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Código',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category'),
        ),
    ]
