# Generated by Django 4.2.5 on 2023-11-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0003_category_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, to='cpadmin.category'),
        ),
    ]
