# Generated by Django 4.2.5 on 2023-11-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0004_remove_category_parent_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
