# Generated by Django 4.2.5 on 2023-11-28 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0005_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.brand'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category'),
        ),
    ]
