# Generated by Django 4.2.5 on 2023-11-29 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0006_category_parent_alter_weapon_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='availability',
            field=models.CharField(choices=[('E', 'Excelente'), ('C', 'Común'), ('P', 'Pobre'), ('R', 'Raro'), ('A', 'Solo Militares'), ('X', 'Experimental')], default='C', max_length=1),
        ),
    ]
