# Generated by Django 4.2.5 on 2023-11-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0007_alter_category_parent_alter_weapon_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='availability',
            field=models.CharField(choices=[('E', 'Excelente'), ('C', 'Común'), ('P', 'Mala'), ('R', 'Rara'), ('A', 'Solo Militares'), ('X', 'Experimental')], default='C', max_length=1),
        ),
    ]
