from django.shortcuts import render, redirect
import collections.abc
import collections
import csv
from .models import Weapon, Category, Brand, Availability, Concealment, Reliability

collections.MutableMapping = collections.abc.MutableMapping
collections.Mapping = collections.abc.Mapping
import pyrebase

# Firebase Configurations
config = {
    "apiKey": "AIzaSyD3LUVINjIt9XAHvMZyXojbqGv-EXrKeUk",
    "authDomain": "cyberpunk-database.firebaseapp.com",
    "databaseURL": "https://cyberpunk-database.firebaseio.com",
    "projectId": "cyberpunk-database",
    "storageBucket": "cyberpunk-database.appspot.com",
    "messagingSenderId": "492371389033",
    "appId": "1:492371389033:web:03dc0c1000b49c6b5350f8",
    "measurementId": "G-FRRFLZ6T17"
}
firebase = pyrebase.initialize_app(config)
auth_token = firebase.auth()
database = firebase.database()


### Function for Home
def index(request):
    return render(request, 'index.html')


### Functions for Equipment Section
def equipment_home(request):
    return weapons_list(request)


# Show Weapon List
def weapons_list(request):
    weapons = Weapon.objects.all().order_by('name')
    weapons_count = 0
    if weapons:
        weapons_count = len(weapons)

    categories = Category.objects.all().order_by('name')
    brands = Brand.objects.all().order_by('name')
    availabilities = Availability.choices
    concealments = Concealment.choices
    reliabilities = Reliability.choices

    context = {
        'weapons_count': weapons_count,
        'weapons': weapons,
        'categories': categories,
        'brands': brands,
        'availabilities': availabilities,
        'concealments': concealments,
        'reliabilities': reliabilities,
    }
        
    return render(request, 'weapons.html', context)


# Create or Update a Weapon
def weapons_save(request):
    return weapons_list(request)


# Upload Weapons List from CSV
def weapons_upload(request):
    csv_file = request.FILES['csv_file'].read().decode('utf-8').splitlines()
    csv_reader = csv.DictReader(csv_file)

    for row in csv_reader:
        category = Category.objects.get(code=row['category'], parent=None)
        brand, created = Brand.objects.get_or_create(name=row['brand'], defaults={'name': row['brand'], 'description': 'Autogenerated'})

        Weapon.objects.update_or_create(
            id=row['id'],
            defaults=dict(
                name=row['name'],
                category=category,
                brand=brand,
                availability=row['availability'],
                concealment=row['concealment'],
                accuracy=row['accuracy'],
                reliability=row['reliability'],
                range=float(row['range']) if row['range'] != '' else None,
                shots=int(row['shots']) if row['shots'] != '' else None,
                rof=int(row['rof']) if row['shots'] != '' else None,
                damage=row['damage'],
                weight=float(row['weight']),
                cost=int(row['cost']),
            )
        )

    return redirect('weapons')


# Download Weapon List in CSV
def weapons_download(request):
    return weapons_list(request)


# Refresh Weapons List with CSV
def weapons_refresh(request):
    action = request.POST['action']
    if action == 'upload': 
        weapons_local = Weapon.objects.all().order_by('id').values()
        for weapon in weapons_local:
            weapon_id = weapon['id']
            weapon_origin = None
            if database.child('weapons').get():
                weapon_origin = database.child('weapons').child(weapon_id).get().val()
            if weapon_origin:
                database.child('weapons').child(weapon_id).set(weapon)
            else:
                database.child('weapons').push(weapon)
    else:
        weapons_origin = database.child('weapons').get()
        for obj in weapons_origin:
            weapon_id = obj.key()
            weapon = obj.val()
            Weapon.objects.update_or_create(
                id=weapon_id,
                name=weapon.name,
                category=weapon.category,
                brand=weapon.brand,
                availability=weapon.availability,
                concealment=weapon.concealment,
                accuracy=weapon.accuracy,
                reliability=weapon.realiability,
                range=weapon.range,
                shots=weapon.shots,
                rof=weapon.rof,
                damage=weapon.damage,
                weight=weapon.weight,
                cost=weapon.cost,
            )
    return weapons_list(request)
    
